services:
  amoeba:
    build: .
    container_name: amoeba
    user: postgres
    # environment:
      # PGHOST: postgres-12
      # PGUSER: postgres
      # PGPASSWORD: postgres
      # PGDATABASE: postgres
    networks:
      - mynet
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    working_dir: /workspace

networks:
  mynet:
    external: true