services:
  sqlancer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sqlancer
    networks:
      - mynet
    tty: true
    stdin_open: true
    volumes:
      - ./sqlancer-logs:/home/sqlancer/target/logs

networks:
  mynet:
    external: true